### PR TITLE
Thirsty2 add docker instructions to readme

### PR DESCRIPTION
**Pull request by Thirsty2**

### CODE REVIEW

**Review by kkumar23 — COMMENTED** [review]
The solution of having docker image is good. Again user should not get confused on having lot many options and choose which is the best.  For the docker to run, i believe we need to mention the steps to install docker or point to the process to install

**Comment by Thirsty2** [comment]
Yes, it is probably worth adding a link to the Docker website and tutorials at least.  There are many other options for running containers, but Docker is perhaps the most popular.  It is surprisingly easy to learn, and anyone can become reasonably proficient pretty quickly.

I would like to simplify the options soon, but I may need some help as I am new to SymbiFlow and I don't know how Quicklogic builds its installer.  Ideally, the Dockerfile that builds Symbiflow from source should also build the installer, and the default final target should run the installer.  This would eliminate the need for the other Dockerfile named Dockerfile.use-installer.  We can use the --target option to build and tag any of the intermediate containers on the path to the final target.  Building and tagging some of the earlier intermediate containers can allow developers to debug the code or any failing tests in a container, while the default target can be stripped of source and extraneous artifacts so that it is as small as possible.

**Comment by Thirsty2** [comment]
I added some high level information on containers, and a link to the docker website which contains tutorials on installing and running Docker.

**Comment by kkumar23** [comment]
@Thirsty2 docker run is failing

**Comment by Thirsty2** [comment]
Looks like it was unable to install conda inside the container, likely due to a conda server side issue:

CondaHTTPError: HTTP 504 GATEWAY TIME-OUT for url <https://conda.anaconda.org/quicklogic-corp/label/ql/noarch/repodata.json>
Elapsed: 01:00.102535
CF-RAY: 5dd5bc9f1b25e0e2-IAD

A remote server error occurred when trying to retrieve this URL.

A 500-type error (e.g. 500, 501, 502, 503, etc.) indicates the server failed to
fulfill a valid request.  The problem may be spurious, and will resolve itself if you
try your request again.  If the problem persists, consider notifying the maintainer
of the remote server.


I will try building locally with 
docker build . -t symbiflow-ql-slim-buster --no-cache

**Comment by Thirsty2** [comment]
The Docker build worked fine locally just now, so I suspect the issue was server side as noted above.  I have updated the Thirsty2 fork using a pull request from QuickLogic-Corp/quicklogic-fpga-toolchain, so the two repos are in sync, and the Docker image is currently building in github actions in the Thirsty2 fork.  It should work assuming no server side issues pulling conda.  I don't know how to get the build to retry when there are spurious errors like this.  Ideally it would retry without having to rebuild all of the docker cached layers that succeeded.  Maybe something could be done in the build script.

**Comment by Thirsty2** [comment]
The Docker build succeeded on the Thirsty2 fork, which is more evidence that a temporary conda server side outage caused the original build failure.

**Comment by Thirsty2** [comment]
You should be able to trigger a new build by clicking the 'Run Workflow' button available to privileged users under Actions->Workflows->All Workflows->Docker.  I see this button next to the text 'This workflow has a workflow_dispatch event trigger' in the Thirsty2 fork, but I don't see it in the QuickLogic repo, but I suspect this is because I am not an admin there.

**Pull request merged**
