### PR TITLE
docs integration : update markdown to rst and add additional info

### PR DESCRIPTION
**Pull request by coolbreeze413**

### CODE REVIEW

**Comment by coolbreeze413** [comment]
Added the (latest) dailybuild instructions as a method to install and use the fpga toolchain.
Hope this is ok, as I think it will be useful for users wanting the latest packages, without build from sources.

**Comment by coolbreeze413** [comment]
added note for the `antlr` being introduced in the Symbiflow fasm repo, and a way to manually install this if needed.

**Comment by kkumar23** [comment]
@coolbreeze413  : I am not sure about the daily builds at this location, as it has only the release specific info or compile from source.

**Comment by kkumar23** [comment]
@tpagarani Please review this.

**Comment by tpagarani** [comment]
@kkumar23 I believe you want my opinion on whether or not we should include daily build in this document. We can skip listing details steps as symbiflow community is already aware of the google storage space. 

We have to start moving towards merging our examples into symbiflow-examples rather than keeping a separate repo altogether.

**Comment by coolbreeze413** [comment]
removed dailybuild steps as per review, it is not needed for public usage.

**Pull request merged**
